**Homework 1: Introduction to Machine Learning for Machine Learning Zoomcamp 2024**

In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



In [78]:
# Question 1

pd.__version__

'2.2.2'

In [79]:
# Question 2

df = pd.read_csv(r'C:\Users\Ana Belen\Documents\Github\Datatalks\laptops.csv')
df.shape

(2160, 12)

In [80]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [81]:
# Question 3

df['Brand'].unique()


array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [82]:
df['Brand'].unique().size

27

In [83]:
# Question 4

df.isna().sum()


Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [84]:
# Question 5

max_value = df[df["Brand"] == "Dell"]["Final Price"].max()
print(float(max_value))


3936.0


In [85]:
# Question 6

median_value = df["Screen"].median()
print(median_value)

15.6


In [86]:
mode = df["Screen"].mode()[0]
print(mode)



15.6


In [87]:
df["Screen"] = df["Screen"].fillna(mode)
print(df["Screen"].isna().sum())


0


In [88]:
median_value = df["Screen"].median()
print(median_value)

15.6


In [89]:
# Question 7

X = df[df["Brand"] == "Innjoo"][["RAM", "Storage", "Screen"]].values
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [90]:
XTX = X.T @X
print(XTX)


[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [91]:
XTX_inv = np.linalg.inv(XTX)


In [92]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
w = XTX_inv @ X.T @ y
result_sum = np.sum(w)
print("Sum of all elements in w:", result_sum)

Sum of all elements in w: 91.2998806299555
